-- Create Books Table
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(100),
    AUTHOR VARCHAR(50),
    GENRE VARCHAR(50),
    PUBLISHED_YEAR INT,
    PRICE NUMERIC(10, 2),
    STOCK INT
);

-- Create Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(30),
    CITY VARCHAR(30),
    COUNTRY VARCHAR(100)
);

-- Create Orders Table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT REFERENCES CUSTOMERS (CUSTOMER_ID),
    BOOK_ID INT REFERENCES BOOKS (BOOK_ID),
    ORDER_DATE DATE,
    QUANTITY INT,
    TOTAL_AMOUNT NUMERIC(10, 2)
);
